steps:
  # Tahap 1: Build Docker image dengan build-args
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_FIREBASE_API_KEY=$_VITE_FIREBASE_API_KEY'
      - '--build-arg'
      - 'VITE_FIREBASE_AUTH_DOMAIN=$_VITE_FIREBASE_AUTH_DOMAIN'
      - '--build-arg'
      - 'VITE_FIREBASE_PROJECT_ID=$_VITE_FIREBASE_PROJECT_ID'
      - '--build-arg'
      - 'VITE_FIREBASE_STORAGE_BUCKET=$_VITE_FIREBASE_STORAGE_BUCKET'
      - '--build-arg'
      - 'VITE_FIREBASE_MESSAGING_SENDER_ID=$_VITE_FIREBASE_MESSAGING_SENDER_ID'
      - '--build-arg'
      - 'VITE_FIREBASE_APP_ID=$_VITE_FIREBASE_APP_ID'
      - '--build-arg'
      - 'VITE_FIREBASE_MEASUREMENT_ID=$_VITE_FIREBASE_MEASUREMENT_ID'
      - '--build-arg'
      - 'VITE_GEMINI_API_KEY=$_VITE_GEMINI_API_KEY'
      - '-t'
      - 'gcr.io/modapos/github.com/zakyvangobel15/modapos:$COMMIT_SHA'
      - '.'

  # Tahap 2: Push image ke Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/modapos/github.com/zakyvangobel15/modapos:$COMMIT_SHA'

  # Tahap 3: Deploy image ke Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'modapos'
      - '--image'
      - 'gcr.io/modapos/github.com/zakyvangobel15/modapos:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast2'
      - '--platform'
      - 'managed'

images:
  - 'gcr.io/modapos/github.com/zakyvangobel15/modapos:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
